In [2]:
import torch

In [5]:
a = 1
t1 = torch.tensor(1)
t1

tensor(1)

# 从NumPy创建
1. 内存共享

In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr)
t

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [11]:
arr[0][0] = 100
arr
t

tensor([[100,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)

In [12]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
a[0][0] = 100
a

tensor([[100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

In [16]:
b = torch.zeros_like(a)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
c = torch.ones(5,5)
c

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
d =  torch.full([2,3],5)
d

tensor([[5, 5, 5],
        [5, 5, 5]])

In [21]:
points = torch.full([3,3],6)
points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [24]:
torch.save(points, './outpoints.t')
new_points = torch.load('./outpoints.t')
new_points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [25]:
pip install h5py


Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Note: you may need to restart the kernel to use updated packages.
