In [1]:
import torch

# 张量的基本操作
1.张量的拼接

In [4]:
a = torch.ones((4,5))
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [6]:
cat_a = torch.cat([a,a], dim=0)
cat_a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [7]:
cat_a2 = torch.cat([a,a], dim=1)
cat_a2

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
a = torch.normal(0,1,(3,4))
b = torch.normal(0,1,(3,4))

In [13]:
cat_ab1 = torch.stack([a,b], dim=0)
cat_ab1

tensor([[[ 0.4536,  0.1044,  0.8034,  0.6739],
         [ 0.3862, -1.5662, -0.6943, -1.0000],
         [ 1.4810,  1.1745,  0.3194, -1.1776]],

        [[-2.2806,  1.0424, -1.7209,  0.9751],
         [ 1.9454, -0.3290, -0.4254, -0.4425],
         [-0.0463, -2.2191,  0.4244,  0.8410]]])

In [14]:
cat_ab2 = torch.stack([a,b], dim=2)
cat_ab2

tensor([[[ 0.4536, -2.2806],
         [ 0.1044,  1.0424],
         [ 0.8034, -1.7209],
         [ 0.6739,  0.9751]],

        [[ 0.3862,  1.9454],
         [-1.5662, -0.3290],
         [-0.6943, -0.4254],
         [-1.0000, -0.4425]],

        [[ 1.4810, -0.0463],
         [ 1.1745, -2.2191],
         [ 0.3194,  0.4244],
         [-1.1776,  0.8410]]])

# 张量的切分

In [15]:
a = torch.ones((3,7))
chunked_a = torch.chunk(a,3,1)
chunked_a

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [16]:
split_a1 = torch.split(a,4,1)
split_a1

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [17]:
points = torch.tensor([[4,1],[5,4],[2,1]])
idx = torch.tensor([0,2])
res = torch.index_select(points, dim=0,index=idx)
res

tensor([[4, 1],
        [2, 1]])

In [18]:
mask = points.ge(3)
mask

tensor([[ True, False],
        [ True,  True],
        [False, False]])

In [19]:
res = torch.masked_select(points,mask)
res

tensor([4, 5, 4])