# 张量底层实现的逻辑
1. 块状连续存储
2. 带状联系存储
## 偏移量和步长进行索引

In [ ]:
## 使用storage访问内存

In [2]:
import torch

In [4]:
points = torch.tensor([[4,1],[5,3],[1,2]])
storage = points.storage()
storage[0]
storage

 4
 1
 5
 3
 1
 2
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [6]:
points = torch.tensor([[4,1,3,2],[5,3,7,8],[1,2,9,5],[3,8,4,5]])
second_point = points[1:,1:]
second_point

tensor([[3, 7, 8],
        [2, 9, 5],
        [8, 4, 5]])

In [7]:
points.storage_offset()

0

In [8]:
second_point.storage_offset()

5

In [9]:
points.stride()

(4, 1)

In [10]:
second_point.stride()

(4, 1)

 # 同一个存储所以步长一致
 

In [12]:
second_point = points[1:,1:].clone()
second_point.stride()

(3, 1)

In [13]:
second_point[0,0] = 10
second_point

tensor([[10,  7,  8],
        [ 2,  9,  5],
        [ 8,  4,  5]])

In [14]:
points

tensor([[4, 1, 3, 2],
        [5, 3, 7, 8],
        [1, 2, 9, 5],
        [3, 8, 4, 5]])

# 转置

In [20]:
points = torch.tensor([[4,1],[5,3],[2,1]])
points

point_t = points.t()
point_t

tensor([[4, 5, 2],
        [1, 3, 1]])

In [24]:
points = torch.tensor([[4,1],[5,3],[2,1]])

point_t = points.t()
point_t
id(point_t.storage()) == id(points.storage())

True

In [25]:
points.stride()

(2, 1)

In [26]:
point_t.stride()

(1, 2)

In [27]:
points.is_contiguous()

True

In [28]:
point_t.is_contiguous()

False